/*
import { FuseNavigationItem } from '@fuse/components/navigation';

let navigations: FuseNavigationItem[] = [
    {
        icon: 'home',
        menuId: 2,
        id: 'home',
        title: 'صفحه اصلی',
        type: 'basic',
        parentId: 1,
        translate: 'home',
        link: '/main/home',
        children: [],
    },
    {
        icon: 'home',
        menuId: 3,
        id: 'clients',
        title: 'مشتریان و پیکره بندی',
        type: 'collapsable',
        parentId: 1,
        translate: 'مشتریان و پیکره بندی',
        children: [
            {
                icon: 'home',
                menuId: 4,
                id: 'clients',
                title: 'مشتریان حقیقی',
                type: 'collapsable',
                parentId: 3,
                translate: 'مشتریان حقیقی',
                children: [
                    {
                        icon: 'home',
                        menuId: 5,
                        id: 'client-citizen',
                        title: 'مدیریت مشتریان حقیقی',
                        type: 'basic',
                        parentId: 4,
                        translate: 'مدیریت مشتریان حقیقی',
                        link: '/main/client-citizen',
                        children: [],
                    },
                    {
                        icon: 'home',
                        menuId: 6,
                        id: 'client-guest',
                        title: 'مدیریت مشتریان میهمان',
                        type: 'basic',
                        parentId: 4,
                        translate: 'مدیریت مشتریان میهمان',
                        link: '/main/client-guest',
                        children: [],
                    },
                    {
                        icon: 'home',
                        menuId: 7,
                        id: 'guest-reason',
                        title: 'مدیریت دلایل مراجعه مشتریان مهمان',
                        type: 'basic',
                        parentId: 4,
                        translate: 'مدیریت دلایل مراجعه مشتریان مهمان',
                        link: '/main/guest-reason',
                        children: [],
                    },

                ]
            },
            {
                icon: 'home',
                menuId: 8,
                id: 'clients',
                title: 'مشتریان حقوقی',
                type: 'collapsable',
                parentId: 3,
                translate: 'مشتریان حقوقی',
                children: [
                    {
                        icon: 'home',
                        menuId: 9,
                        id: 'client-corporate',
                        title: 'مدیریت مشتریان حقوقی',
                        type: 'basic',
                        parentId: 3,
                        translate: 'مدیریت مشتریان حقوقی',
                        link: '/main/client-corporate',
                        children: [
                            {
                                icon: 'home',
                                menuId: 10,
                                id: 'not-established',
                                title: 'در شرف تاسیس',
                                type: 'basic',
                                parentId: 9,
                                translate: 'در شرف تاسیس',
                                link: '/main/not-established',
                                children: [],
                            },
                        ],
                    },


                ],
            },
        ]
    },
    {
        icon: 'home',
        menuId: 11,
        id: 'product',
        title: 'محصول',
        type: 'collapsable',
        parentId: 1,
        translate: 'محصول',
        children: [
            {
                icon: 'home',
                menuId: 12,
                id: 's',
                title: 'مدیریت محصول',
                type: 'basic',
                parentId: 11,
                translate: 'مدیریت محصول',
                link: '/main/product-management',
                children: [],
            },
        ]
    },
    {
        icon: 'home',
        menuId: 13,
        id: 'clients',
        title: 'مدیریت پارامتر ها',
        type: 'collapsable',
        parentId: 1,
        translate: 'مدیریت پارامتر ها',
        children: [
            {
                icon: 'home',
                menuId: 14,
                id: 'client-citizen',
                title: 'اطلاعات پایه',
                type: 'basic',
                parentId: 13,
                translate: 'مشتریان حقیقی',
                link: '/main/basic-info',
                children: [],
            },
        ]
    },
    {
        icon: 'home',
        menuId: 14,
        id: 'loan-management',
        title: 'مدیریت تسهیلات',
        type: 'collapsable',
        parentId: 1,
        translate: 'مدیریت تسهیلات',
        children: [
            {
                icon: 'home',
                menuId: 15,
                id: 'loan-product',
                title: 'محصول',
                type: 'basic',
                parentId: 14,
                translate: 'محصول',
                link: '/main/lon-product',
                children: [],
            },
            {
                icon: 'home',
                menuId: 16,
                id: 'loan-funding-sources',
                title: 'تعهدات',
                type: 'basic',
                parentId: 14,
                translate: 'تعهدات',
                link: '/main/loan-funding-sources',
                children: [],
            },
            {
                icon: 'home',
                menuId: 17,
                id: 'loan-goal',
                title: 'اهداف از دریافت تسهیلات',
                type: 'basic',
                parentId: 14,
                translate: 'اهداف از دریافت تسهیلات',
                link: '/main/loan-goal',
                children: [],
            },
            {
                icon: 'home',
                menuId: 18,
                id: 'loan-usage',
                title: 'استفاده از تسهیلات',
                type: 'basic',
                parentId: 14,
                translate: 'استفاده از تسهیلات',
                link: '/main/loan-usage',
                children: [],
            },
            {
                icon: 'home',
                menuId: 19,
                id: 'loan-type',
                title: 'انواع عقد',
                type: 'basic',
                parentId: 14,
                translate: 'انواع عقد',
                link: '/main/loan-type',
                children: [],
            },
            {
                icon: 'home',
                menuId: 20,
                id: 'loan-operation',
                title: 'عملیات',
                type: 'basic',
                parentId: 14,
                translate: 'عملیات',
                link: '/main/loan-operation',
                children: [],
            },
            {
                icon: 'home',
                menuId: 21,
                id: 'loan-pattern-operation',
                title: 'الگوی عملیات',
                type: 'basic',
                parentId: 14,
                translate: 'الگوی عملیات',
                link: '/main/loan-pattern-operation',
                children: [],
            },
            {
                icon: 'home',
                menuId: 22,
                id: 'loan-plan-type',
                title: 'انواع طرح/پرونده تسهیلات',
                type: 'basic',
                parentId: 14,
                translate: 'انواع طرح/پرونده تسهیلات',
                link: '/main/lon-plan-type',
                children: [],
            },
            {
                icon: 'home',
                menuId: 23,
                id: 'loan-request',
                title: 'انواع درخواست‌های تسهیلات',
                type: 'basic',
                parentId: 14,
                translate: 'انواع درخواست‌های تسهیلات',
                link: '/main/lon-request',
                children: [],
            },
            {
                icon: 'home',
                menuId: 24,
                id: 'loan-sub-operation',
                title: 'ریز عملیات',
                type: 'basic',
                parentId: 14,
                translate: 'ریز عملیات',
                link: '/main/lon-sub-operation',
                children: [],
            },
            {
                icon: 'home',
                menuId: 25,
                id: 'loan-contract',
                title: 'ثبت قرار داد تسهیلات',
                type: 'basic',
                parentId: 14,
                translate: 'ثبت قرار داد تسهیلات',
                link: '/main/loan-contract',
                children: [],
            },
            {
                icon: 'home',
                menuId: 26,
                id: 'loan-contract-grant',
                title: 'پرداخت تسهیلات',
                type: 'basic',
                parentId: 14,
                translate: 'پرداخت تسهیلات',
                link: '/main/loan-contract-grant',
                children: [],
            },
            {
                icon: 'home',
                menuId: 27,
                id: 'loan-contract-grant',
                title: 'معرفی مرتبطین',
                type: 'basic',
                parentId: 14,
                translate: 'معرفی مرتبطین',
                link: '/main/loan-involved-customer',
                children: [],
            },
            {
                icon: 'home',
                menuId: 28,
                id: 'loan-contract-grant',
                title: 'تنظیم پیشنهاد تسهیلات',
                type: 'basic',
                parentId: 14,
                translate: 'تنظیم پیشنهاد تسهیلات',
                link: '/main/loan-proposed',
                children: [],
            },
            {
                icon: 'home',
                menuId: 29,
                id: 'loan-refound',
                title: 'بازپرداخت تسهیلات ',
                type: 'basic',
                parentId: 14,
                translate: 'بازپرداخت تسهیلات ',
                link: '/main/loan-refound',
                children: [],
            },
            {
                icon: 'home',
                menuId: 30,
                id: 'loan-request',
                title: 'درخواست تسهیلات',
                type: 'basic',
                parentId: 14,
                translate: 'درخواست تسهیلات',
                link: '/main/loan-request',
                children: [],
            },
            {
                icon: 'home',
                menuId: 31,
                id: 'loan-settlment',
                title: 'تسویه تسهیلات',
                type: 'basic',
                parentId: 14,
                translate: 'تسویه تسهیلات',
                link: '/main/loan-settlment',
                children: [],
            },
        ],
    },
    {
        icon: 'exit_to_app',
        menuId: 7,
        id: 'logout',
        title: 'خروج',
        type: 'basic',
        parentId: 1,
        translate: 'خروج',
        link: '/000000000',
        children: [],
    },
];
export const defaultNavigation: FuseNavigationItem[] = navigations;
export const compactNavigation: FuseNavigationItem[] = navigations;
export const futuristicNavigation: FuseNavigationItem[] = navigations;
export const horizontalNavigation: FuseNavigationItem[] = navigations;
*/
import { FuseNavigationItem } from '@fuse/components/navigation';

let navigations: FuseNavigationItem[] = [
    {
        icon: 'home',
        menuId: 2,
        id: 'home',
        title: 'صفحه اصلی',
        type: 'basic',
        parentId: 1,
        translate: 'home',
        link: '/main/home',
        children: [],
    },
    {
        icon: 'home',
        menuId: 3,
        id: 'clients-config',
        title: 'مشتریان و پیکره بندی',
        type: 'collapsable',
        parentId: 1,
        translate: 'مشتریان و پیکره بندی',
        children: [
            {
                icon: 'home',
                menuId: 4,
                id: 'clients-individual',
                title: 'مشتریان حقیقی',
                type: 'collapsable',
                parentId: 3,
                translate: 'مشتریان حقیقی',
                children: [
                    {
                        icon: 'home',
                        menuId: 5,
                        id: 'client-individual-management',
                        title: 'مدیریت مشتریان حقیقی',
                        type: 'basic',
                        parentId: 4,
                        translate: 'مدیریت مشتریان حقیقی',
                        link: '/main/client-citizen',
                        children: [],
                    },
                    {
                        icon: 'home',
                        menuId: 6,
                        id: 'client-guest-management',
                        title: 'مدیریت مشتریان میهمان',
                        type: 'basic',
                        parentId: 4,
                        translate: 'مدیریت مشتریان میهمان',
                        link: '/main/client-guest',
                        children: [],
                    },
                    {
                        icon: 'home',
                        menuId: 7,
                        id: 'guest-reason-management',
                        title: 'مدیریت دلایل مراجعه مشتریان مهمان',
                        type: 'basic',
                        parentId: 4,
                        translate: 'مدیریت دلایل مراجعه مشتریان مهمان',
                        link: '/main/guest-reason',
                        children: [],
                    },

                ]
            },
            {
                icon: 'home',
                menuId: 8,
                id: 'clients-corporate',
                title: 'مشتریان حقوقی',
                type: 'collapsable',
                parentId: 3,
                translate: 'مشتریان حقوقی',
                children: [
                    {
                        icon: 'home',
                        menuId: 9,
                        id: 'client-corporate-management',
                        title: 'مدیریت مشتریان حقوقی',
                        type: 'basic',
                        parentId: 3,
                        translate: 'مدیریت مشتریان حقوقی',
                        link: '/main/client-corporate',
                        children: [
                            {
                                icon: 'home',
                                menuId: 10,
                                id: 'corporate-not-established',
                                title: 'در شرف تاسیس',
                                type: 'basic',
                                parentId: 9,
                                translate: 'در شرف تاسیس',
                                link: '/main/not-established',
                                children: [],
                            },
                        ],
                    },
                ],
            },
        ]
    },
    {
        icon: 'home',
        menuId: 11,
        id: 'product',
        title: 'محصول',
        type: 'collapsable',
        parentId: 1,
        translate: 'محصول',
        children: [
            {
                icon: 'home',
                menuId: 12,
                id: 'product-management',
                title: 'مدیریت محصول',
                type: 'basic',
                parentId: 11,
                translate: 'مدیریت محصول',
                link: '/main/product-management',
                children: [],
            },
        ]
    },
    {
        icon: 'home',
        menuId: 13,
        id: 'parameter-management',
        title: 'مدیریت پارامتر ها',
        type: 'collapsable',
        parentId: 1,
        translate: 'مدیریت پارامتر ها',
        children: [
            {
                icon: 'home',
                menuId: 14,
                id: 'basic-info',
                title: 'اطلاعات پایه',
                type: 'basic',
                parentId: 13,
                translate: 'مشتریان حقیقی',
                link: '/main/basic-info',
                children: [],
            },
        ]
    },
    {
        icon: 'home',
        menuId: 14,
        id: 'loan-management',
        title: 'مدیریت تسهیلات',
        type: 'collapsable',
        parentId: 1,
        translate: 'مدیریت تسهیلات',
        children: [
            {
                icon: 'home',
                menuId: 10,
                id: 'loan-product',
                title: 'محصول',
                type: 'basic',
                parentId: 8,
                translate: 'محصول',
                link: '/main/lon-product',
                children: [],
            },
            {
                icon: 'home',
                menuId: 11,
                id: 'loan-funding-sources',
                title: 'تعهدات',
                type: 'basic',
                parentId: 8,
                translate: 'تعهدات',
                link: '/main/loan-funding-sources',
                children: [],
            },
            {
                icon: 'home',
                menuId: 12,
                id: 'loan-goal',
                title: 'اهداف از دریافت تسهیلات',
                type: 'basic',
                parentId: 8,
                translate: 'اهداف از دریافت تسهیلات',
                link: '/main/loan-goal',
                children: [],
            },
            {
                icon: 'home',
                menuId: 13,
                id: 'loan-usage',
                title: 'استفاده از تسهیلات',
                type: 'basic',
                parentId: 8,
                translate: 'استفاده از تسهیلات',
                link: '/main/loan-usage',
                children: [],
            },
            {
                icon: 'home',
                menuId: 14,
                id: 'loan-type',
                title: 'انواع عقد',
                type: 'basic',
                parentId: 8,
                translate: 'انواع عقد',
                link: '/main/loan-type',
                children: [],
            },
            {
                icon: 'home',
                menuId: 15,
                id: 'loan-operation',
                title: 'عملیات',
                type: 'basic',
                parentId: 8,
                translate: 'عملیات',
                link: '/main/loan-operation',
                children: [],
            },
            {
                icon: 'home',
                menuId: 16,
                id: 'loan-pattern-operation',
                title: 'الگوی عملیات',
                type: 'basic',
                parentId: 8,
                translate: 'الگوی عملیات',
                link: '/main/loan-pattern-operation',
                children: [],
            },
            {
                icon: 'home',
                menuId: 17,
                id: 'loan-plan-type',
                title: 'انواع طرح/پرونده تسهیلات',
                type: 'basic',
                parentId: 8,
                translate: 'انواع طرح/پرونده تسهیلات',
                link: '/main/lon-plan-type',
                children: [],
            },
            {
                icon: 'home',
                menuId: 18,
                id: 'loan-request',
                title: 'انواع درخواست‌های تسهیلات',
                type: 'basic',
                parentId: 8,
                translate: 'انواع درخواست‌های تسهیلات',
                link: '/main/lon-request',
                children: [],
            },
            {
                icon: 'home',
                menuId: 19,
                id: 'loan-sub-operation',
                title: 'ریز عملیات',
                type: 'basic',
                parentId: 8,
                translate: 'ریز عملیات',
                link: '/main/lon-sub-operation',
                children: [],
            },
            {
                icon: 'home',
                menuId: 20,
                id: 'loan-contract',
                title: 'ثبت قرار داد تسهیلات',
                type: 'basic',
                parentId: 8,
                translate: 'ثبت قرار داد تسهیلات',
                link: '/main/loan-contract',
                children: [],
            },
            {
                icon: 'home',
                menuId: 21,
                id: 'loan-contract-grant',
                title: 'پرداخت تسهیلات',
                type: 'basic',
                parentId: 8,
                translate: 'پرداخت تسهیلات',
                link: '/main/loan-contract-grant',
                children: [],
            },
            {
                icon: 'home',
                menuId: 22,
                id: 'loan-contract-grant',
                title: 'معرفی مرتبطین',
                type: 'basic',
                parentId: 8,
                translate: 'معرفی مرتبطین',
                link: '/main/loan-involved-customer',
                children: [],
            },
            {
                icon: 'home',
                menuId: 23,
                id: 'loan-contract-grant',
                title: 'تنظیم پیشنهاد تسهیلات',
                type: 'basic',
                parentId: 8,
                translate: 'تنظیم پیشنهاد تسهیلات',
                link: '/main/loan-proposed',
                children: [],
            },
            {
                icon: 'home',
                menuId: 24,
                id: 'loan-refound',
                title: 'بازپرداخت تسهیلات ',
                type: 'basic',
                parentId: 8,
                translate: 'بازپرداخت تسهیلات ',
                link: '/main/loan-refound',
                children: [],
            },
            {
                icon: 'home',
                menuId: 25,
                id: 'loan-request',
                title: 'درخواست تسهیلات',
                type: 'basic',
                parentId: 8,
                translate: 'درخواست تسهیلات',
                link: '/main/loan-request',
                children: [],
            },
            {
                icon: 'home',
                menuId: 26,
                id: 'loan-settlment',
                title: 'تسویه تسهیلات',
                type: 'basic',
                parentId: 8,
                translate: 'تسویه تسهیلات',
                link: '/main/loan-settlment',
                children: [],
            },
        ],
    },
    {
        icon: 'exit_to_app',
        menuId: 7,
        id: 'logout',
        title: 'خروج',
        type: 'basic',
        parentId: 1,
        translate: 'خروج',
        link: '/000000000',
        children: [],
    },
];

export const defaultNavigation: FuseNavigationItem[] = navigations;
export const compactNavigation: FuseNavigationItem[] = navigations;
export const futuristicNavigation: FuseNavigationItem[] = navigations;
export const horizontalNavigation: FuseNavigationItem[] = navigations;
