/* eslint-disable */
import { FuseNavigationItem } from '@fuse/components/navigation';

let navigations: FuseNavigationItem[] = [
    {
        icon: 'home',
        menuId: 2,
        id: 'home',
        title: 'صفحه اصلی',
        type: 'basic',
        parentId: 1,
        translate: 'home',
        link: '/main/home',
        children: [],
    },
    {
        icon: 'home',
        menuId: 3,
        id: 'clients',
        title: 'مشتریان',
        type: 'collapsable',
        parentId: 1,
        translate: 'مشتریان',
        children: [
            {
                icon: 'home',
                menuId: 4,
                id: 'client-citizen',
                title: 'مشتریان حقیقی',
                type: 'basic',
                parentId: 3,
                translate: 'مشتریان حقیقی',
                link: '/main/client-citizen',
                children: [],
            },
            {
                icon: 'home',
                menuId: 5,
                id: 'client-corporate',
                title: 'مشتریان حقوقی',
                type: 'basic',
                parentId: 3,
                translate: 'مشتریان حقوقی',
                link: '/main/client-corporate',
                children: [],
            },
            {
                icon: 'home',
                menuId: 24,
                id: 'not-established',
                title: 'در شرف تاسیس',
                type: 'basic',
                parentId: 3,
                translate: 'در شرف تاسیس',
                link: '/main/not-established',
                children: [],
            },
            {
                icon: 'home',
                menuId: 7,
                id: 'client-guest',
                title: 'مشتریان میهمان',
                type: 'basic',
                parentId: 3,
                translate: 'مشتریان میهمان',
                link: '/main/client-guest',
                children: [],
            },
            {
                icon: 'home',
                menuId: 6,
                id: 'guest-reason',
                title: 'مدیریت دلایل مراجعه مشتریان مهمان',
                type: 'basic',
                parentId: 3,
                translate: 'مدیریت دلایل مراجعه مشتریان مهمان',
                link: '/main/guest-reason',
                children: [],
            },
            {
                icon: 'home',
                menuId: 22,
                id: 'product',
                title: 'محصول',
                type: 'collapsable',
                parentId: 3,
                translate: 'محصول',
                children: [
                    {
                        icon: 'home',
                        menuId: 23,
                        id: 's',
                        title: 'مدیریت محصول',
                        type: 'basic',
                        parentId: 22,
                        translate: 'مدیریت محصول',
                        link: '/main/product-management',
                        children: [],
                    },
                ]
            },
        ],
    },
    {
        icon: 'home',
        menuId: 8,
        id: 'loan-management',
        title: 'مدیریت تسهیلات',
        type: 'collapsable',
        parentId: 1,
        translate: 'مدیریت تسهیلات',
        children: [
            {
                icon: 'home',
                menuId: 10,
                id: 'loan-product',
                title: 'محصول',
                type: 'basic',
                parentId: 8,
                translate: 'محصول',
                link: '/main/lon-product',
                children: [],
            },
            {
                icon: 'home',
                menuId: 11,
                id: 'loan-funding-sources',
                title: 'تعهدات',
                type: 'basic',
                parentId: 8,
                translate: 'تعهدات',
                link: '/main/loan-funding-sources',
                children: [],
            },
            {
                icon: 'home',
                menuId: 12,
                id: 'loan-goal',
                title: 'اهداف از دریافت تسهیلات',
                type: 'basic',
                parentId: 8,
                translate: 'اهداف از دریافت تسهیلات',
                link: '/main/loan-goal',
                children: [],
            },
            {
                icon: 'home',
                menuId: 13,
                id: 'loan-usage',
                title: 'استفاده از تسهیلات',
                type: 'basic',
                parentId: 8,
                translate: 'استفاده از تسهیلات',
                link: '/main/loan-usage',
                children: [],
            },
            {
                icon: 'home',
                menuId: 14,
                id: 'loan-type',
                title: 'انواع عقد',
                type: 'basic',
                parentId: 8,
                translate: 'انواع عقد',
                link: '/main/loan-type',
                children: [],
            },
            {
                icon: 'home',
                menuId: 15,
                id: 'loan-operation',
                title: 'عملیات',
                type: 'basic',
                parentId: 8,
                translate: 'عملیات',
                link: '/main/loan-operation',
                children: [],
            },
            {
                icon: 'home',
                menuId: 16,
                id: 'loan-pattern-operation',
                title: 'الگوی عملیات',
                type: 'basic',
                parentId: 8,
                translate: 'الگوی عملیات',
                link: '/main/loan-pattern-operation',
                children: [],
            },
            {
                icon: 'home',
                menuId: 17,
                id: 'loan-plan-type',
                title: 'انواع طرح/پرونده تسهیلات',
                type: 'basic',
                parentId: 8,
                translate: 'انواع طرح/پرونده تسهیلات',
                link: '/main/lon-plan-type',
                children: [],
            },
            {
                icon: 'home',
                menuId: 18,
                id: 'loan-request',
                title: 'انواع درخواست‌های تسهیلات',
                type: 'basic',
                parentId: 8,
                translate: 'انواع درخواست‌های تسهیلات',
                link: '/main/lon-request',
                children: [],
            },
            {
                icon: 'home',
                menuId: 19,
                id: 'loan-sub-operation',
                title: 'ریز عملیات',
                type: 'basic',
                parentId: 8,
                translate: 'ریز عملیات',
                link: '/main/lon-sub-operation',
                children: [],
            },
            {
                icon: 'home',
                menuId: 20,
                id: 'loan-contract',
                title: 'ثبت قرار داد تسهیلات',
                type: 'basic',
                parentId: 8,
                translate: 'ثبت قرار داد تسهیلات',
                link: '/main/loan-contract',
                children: [],
            },
            {
                icon: 'home',
                menuId: 21,
                id: 'loan-contract-grant',
                title: 'پرداخت تسهیلات',
                type: 'basic',
                parentId: 8,
                translate: 'پرداخت تسهیلات',
                link: '/main/loan-contract-grant',
                children: [],
            },
            {
                icon: 'home',
                menuId: 22,
                id: 'loan-contract-grant',
                title: 'معرفی مرتبطین',
                type: 'basic',
                parentId: 8,
                translate: 'معرفی مرتبطین',
                link: '/main/loan-involved-customer',
                children: [],
            },
            {
                icon: 'home',
                menuId: 23,
                id: 'loan-contract-grant',
                title: 'تنظیم پیشنهاد تسهیلات',
                type: 'basic',
                parentId: 8,
                translate: 'تنظیم پیشنهاد تسهیلات',
                link: '/main/loan-proposed',
                children: [],
            },
            {
                icon: 'home',
                menuId: 24,
                id: 'loan-refound',
                title: 'بازپرداخت تسهیلات ',
                type: 'basic',
                parentId: 8,
                translate: 'بازپرداخت تسهیلات ',
                link: '/main/loan-refound',
                children: [],
            },
            {
                icon: 'home',
                menuId: 25,
                id: 'loan-request',
                title: 'درخواست تسهیلات',
                type: 'basic',
                parentId: 8,
                translate: 'درخواست تسهیلات',
                link: '/main/loan-request',
                children: [],
            },
            {
                icon: 'home',
                menuId: 26,
                id: 'loan-settlment',
                title: 'تسویه تسهیلات',
                type: 'basic',
                parentId: 8,
                translate: 'تسویه تسهیلات',
                link: '/main/loan-settlment',
                children: [],
            },
        ],
    },
    {
        icon: 'exit_to_app',
        menuId: 21,
        id: 'logout',
        title: 'خروج',
        type: 'basic',
        parentId: 1,
        translate: 'خروج',
        link: '/000000000',
        children: [],
    },
];
export const defaultNavigation: FuseNavigationItem[] = navigations;
export const compactNavigation: FuseNavigationItem[] = navigations;
export const futuristicNavigation: FuseNavigationItem[] = navigations;
export const horizontalNavigation: FuseNavigationItem[] = navigations;
